version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nodrive
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  traefik:
    image: traefik:v2.9
    depends_on:
      - client
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.routers.api.service=api-vreal
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.client.rule=Host(`localhost`)
      - traefik.http.routers.client.service=client-vreal
      - traefik.http.routers.client.entrypoints=web
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    restart: unless-stopped

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./server
        target: /app
    ports:
      - "3001:3000"

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./client
        target: /app
    ports:
      - "3000:5173"
